### ISSUE TITLE
NoMethodError error in workflow poller

### ISSUE THREAD

**Issue by Tsquare** [aws/aws-flow-ruby#62] opened 2014-08-22 18:59 UTC
I'm seeing intermittent errors like this in the AWS-Flow-WorkflowTaskPoller log file:
I, [2014-07-08T21:43:39.541507 #6052]  INFO -- : Got decision task ...
E, [2014-07-08T21:43:44.207649 #6052] ERROR -- : Error in the poller, NoMethodError, undefined method `consume' for nil:NilClass

For the same flow with the same parameters, etc, we sometimes get this error with the result that decision tasks time out and the flow never completes, and sometimes everything completes normally.

**Comment by pmohan6** [comment] 2015-01-13 23:36
Unfortunately, we are not able to reproduce this issue ourselves. It's possible that there is some state machine bug or some weird race condition but a minimal repro is needed to isolate the issue. Were you able to use the replayer to isolate it? Do you continue to see this issue?

**Comment by Tsquare** [comment] 2015-01-13 23:38
sorry, have not been able to repro with replayer.  the plan is to work around this issue by changing our flow

**Comment by pmohan6** [comment] 2015-01-14 21:29
I'm resolving this issue for now because we haven't been able to repro it and don't have a path forward. Feel free to reopen if you have any new findings.

**Closed by pmohan6** 2015-01-14 21:29 UTC
